# Use Ubuntu 22.04
FROM ubuntu:22.04

# Install necessary packages: wget and the JDK
RUN apt-get update && apt-get install -y \
    wget \
    openjdk-11-jdk

# Set environment variables for Tomcat
ENV TOMCAT_VERSION=9.0.80
ENV TOMCAT_HOME=/opt/tomcat

# Download and extract Tomcat
RUN wget https://archive.apache.org/dist/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz \
    && mkdir -p $TOMCAT_HOME \
    && tar -xvf apache-tomcat-${TOMCAT_VERSION}.tar.gz -C $TOMCAT_HOME --strip-components=1 \
    && rm apache-tomcat-${TOMCAT_VERSION}.tar.gz

# Expose port 8080
EXPOSE 8080

# Set the working directory
WORKDIR $TOMCAT_HOME

# Start Tomcat
CMD ["bin/catalina.sh", "run"]