apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQxMjM=  # Base64 encoded 'password123'
  mysql-user-password: cGFzc3dvcmQxMjM=  # Base64 encoded 'password123'