apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-mysql-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: mysql-pv-2
  storageClassName: standard
