apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-mysql-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: mysql-pv-0
  storageClassName: standard