apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-reader-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: logging
roleRef:
  kind: ClusterRole
  name: fluentd-reader
  apiGroup: rbac.authorization.k8s.io